[package]
name = "ya-runtime-vm"
version = "0.1.1"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"
license = "GPL-3.0"

[package.metadata.deb]
assets = [
    ["conf/ya-runtime-vm.json",         "usr/lib/yagna/plugins/", "644"],
    ["target/release/ya-runtime-vm",    "usr/lib/yagna/plugins/ya-runtime-vm/", "755"],
    ["poc/runtime/bios-256k.bin",       "usr/lib/yagna/plugins/ya-runtime-vm/runtime/", "644"],
    ["poc/runtime/initramfs-virt",      "usr/lib/yagna/plugins/ya-runtime-vm/runtime/", "644"],
    ["poc/runtime/kvmvapic.bin",        "usr/lib/yagna/plugins/ya-runtime-vm/runtime/", "644"],
    ["poc/runtime/linuxboot_dma.bin",   "usr/lib/yagna/plugins/ya-runtime-vm/runtime/", "644"],
    ["poc/runtime/vmlinuz-virt",        "usr/lib/yagna/plugins/ya-runtime-vm/runtime/", "644"],
    ["poc/runtime/vmrt",                "usr/lib/yagna/plugins/ya-runtime-vm/runtime/", "755"]
]

[dependencies]
anyhow = "1.0"
env_logger = "0.7.1"
log = "0.4.8"
num_cpus = "1.13.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
uuid = { version = "0.8", features = ["v4"] }
